version: 2
jobs:
  # TODO: add caching
  python:
    docker:
      - image: themattrix/tox

    steps:
      - checkout
      - run:
          command: pip install tox
          name: Install Tox
      - run:
          command: tox
          name: Run Tox Tests
      - store_test_results:
          path: .tox/tox-*.xml


workflows:
  version: 2
  UnitTests:
    jobs:
      - python
