version: 2
jobs:
  # TODO: add caching
  python:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          command: tox
          name: Run Tox Tests

workflows:
  version: 2
  UnitTests:
    jobs:
      - python
